version: '3'
services:
  web:
    build: .
    ports:
     - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
      
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=~/solution/prometheus.yml
